name: terraform deploye

on:
    push:
        branches:
            master:


jobs:
    terraform:
        runs-on: ubuntu-latest
        
        steps:
          - name: Checkout repositoty
            uses: actions/checkout@v4
          - name: configure the aws credentials
            uses: aws-actions/configure-aws-credentials@v2
            with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-seceret-access-key: ${{ secrets.AWS_SECRET_ACESS_KEY }}
                region: "us-east-1"
          - name: install terraform
            uses: hashicorp/setup-terraform@v3

          - name: terraform init
            run: terraform init
            
          - name: terraform plan
            run: terraform plan
            
          - name: terraform apply
            run: terraform apply  