name: terraform deploye

on:
  push:
    branches:
       - master


jobs:
    terraform:
        runs-on: ubuntu-latest
        
        steps:
          - name: Checkout repositoty    #for downloading code
            uses: actions/checkout@v4
          - name: configure the aws credentials     #for login the AWS 
            uses: aws-actions/configure-aws-credentials@v2
            with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACESS_KEY }}
                aws-region: us-east-1
          - name: install terraform
            uses: hashicorp/setup-terraform@v3        #for installing the terraform 

          - name: terraform init
            run: terraform init
            
          - name: terraform plan
            run: terraform plan
            
          - name: terraform apply
            run: terraform apply  